---
########################################
# ADMIN VM – HEALTH, SLURM & CM INFO
########################################
- name: Collect Admin VM Health & SLURM Info
  hosts: hpcm_admin
  gather_facts: false
  vars:
    output_dir: "/tmp/hpcm_outputs/{{ inventory_hostname }}"
  tasks:

    - name: Create admin output directory
      delegate_to: localhost
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

    - name: Collect Admin VM Data
      shell: |
        set +e
        {
          echo "================ ADMIN VM ================="

          echo "===== Hostname ====="
          hostname

          echo "===== /etc/sgi-admin-node-release ====="
          cat /etc/sgi-admin-node-release || true

          echo "===== Kernel ====="
          uname -r || true

          echo "===== Memory ====="
          free -h || true

          echo "===== IP Addresses (hostname -I) ====="
          hostname -I || true

          echo "===== IP Addresses (ip a) ====="
          ip a || true

          echo "===== DNS ====="
          cat /etc/resolv.conf || true

          echo "===== cmdb.service ====="
          systemctl status cmdb.service || true

          echo "===== clmgr-health ====="
          systemctl status clmgr-health || true

          echo "===== clmgr-power.service ====="
          systemctl status clmgr-power.service || true

          echo "===== CM Network ====="
          cm network show -d -n || true

          echo "===== pdsh hostname (compute) ====="
          pdsh -g compute hostname -I || true

          echo "===== Power Status ====="
          cm power status -t system || true

          echo "===== CM Image ====="
          cm image show || true

          echo "===== CM Monitoring Alerting ====="
          cm monitoring alerting status || true

          echo "===== Compute Uptime ====="
          pdsh -g compute uptime || true

          echo "===== Hardware ====="
          dmidecode -t system || true

          echo "===== SLURM Version ====="
          sinfo --version || true

          echo "===== slurmctld ====="
          systemctl status slurmctld || true

          echo "===== slurmdbd ====="
          systemctl status slurmdbd.service || true

          echo "===== scontrol ping ====="
          scontrol ping || true

          echo "===== sinfo ====="
          sinfo || true

          echo "===== sinfo -R ====="
          sinfo -R || true

          echo "===== sinfo -N ====="
          sinfo -N || true
        } 2>&1
      register: admin_output
      changed_when: false

    - name: Save Admin VM Output
      delegate_to: localhost
      copy:
        content: "{{ admin_output.stdout }}"
        dest: "{{ output_dir }}/admin_vm_health.txt"

    ########################################
    ## CM INFO GATHER (IMPORTANT – LAST)
    ########################################
    # - name: Run cm-info-gather
    #   shell: cm-info-gather
    #   register: cm_info
    #   changed_when: false

    # - name: Save cm-info-gather log
    #   delegate_to: localhost
    #   copy:
    #     content: "{{ cm_info.stdout }}"
    #     dest: "{{ output_dir }}/cm-info-gather.log"

    # - name: Find cm-info-gather archive
    #   shell: ls -t /var/tmp/cm-info-gather-*.tar.bz2 | head -1
    #   register: cm_info_tar
    #   changed_when: false

    # - name: Copy cm-info-gather archive to output directory
    #   fetch:
    #     src: "{{ cm_info_tar.stdout }}"
    #     dest: "{{ output_dir }}/"
    #     flat: yes

########################################
# HPC cluster node
########################################
- name: Collect HPC cluster node
  hosts: compute
  gather_facts: false
  vars:
    output_dir: "/tmp/hpcm_outputs/compute"
  tasks:

    - name: Create compute output directory
      delegate_to: localhost
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

    - name: Collect Compute Local Data
      shell: |
        set +e
        {
          echo "================ COMPUTE NODE ================="

          echo "===== Hostname ====="
          hostname

          echo "===== OS Release ====="
          cat /etc/redhat-release || true

          echo "===== Kernel ====="
          uname -r || true

          echo "===== IP Addresses (ip -br a) ====="
          ip -br a || true

          echo "===== IP Addresses (hostname -I) ====="
          hostname -I || true

          echo "===== Memory ====="
          free -h || true

          echo "===== Disks (lsblk) ====="
          lsblk || true
          
          echo "===== Mounts (df -Th) ====="
          df -Th || true

          echo "===== Hardware ====="
          dmidecode -t system || true

          echo "===== NVIDIA GPU Details ====="
          nvidia-smi || true

          echo "===== CUDA Driver Version ====="
          nvidia-smi | grep -i cuda || true

          echo "===== SLURM Service ====="
          systemctl status slurmd | grep Active || true

          echo "===== Grafana Service ====="
          systemctl status grafana-server | grep Active || true

          echo "===== Prometheus Service ====="
          systemctl status prometheus | grep Active || true

          echo "===== HPCM / CM Services ====="
          cm status || true

          echo "===== InfiniBand Status ====="
          ibstat || true

          echo "===== Mellanox PCI Devices ====="
          lspci | grep -i Mellanox || true

          echo "===== Lustre Client Version ====="
          cat /proc/fs/lustre/version 2>/dev/null || modinfo lustre | grep version || true

        } 2>&1
      register: compute_local
      changed_when: false

    - name: Save Compute Local Output
      delegate_to: localhost
      copy:
        content: "{{ compute_local.stdout }}"
        dest: "{{ output_dir }}/compute_local_health.txt"
########################################
# COMPUTE – CM INVENTORY & MONITORING (gpu001)
########################################
- name: Compute CM Inventory & Monitoring (gpu001)
  hosts: hpcm_admin
  gather_facts: false
  vars:
    output_dir: "/tmp/hpcm_outputs/compute"
  tasks:

    - name: CM Native Monitoring (gpu001)
      shell: cm monitoring native status -e -n gpu001
      register: native_monitoring
      changed_when: false

    - name: Save Native Monitoring
      delegate_to: localhost
      copy:
        content: "{{ native_monitoring.stdout }}"
        dest: "{{ output_dir }}/NativeMonitoring_gpu001.txt"

    - name: CM Firmware (gpu001)
      shell: cm node firmware show -s -n gpu001
      register: firmware
      changed_when: false

    - name: Save Firmware
      delegate_to: localhost
      copy:
        content: "{{ firmware.stdout }}"
        dest: "{{ output_dir }}/Firmware_gpu001.txt"

    - name: CM Inventory (gpu001)
      shell: cm inventory -e -n gpu001
      register: inventory
      changed_when: false

    - name: Save Inventory
      delegate_to: localhost
      copy:
        content: "{{ inventory.stdout }}"
        dest: "{{ output_dir }}/Inventory_gpu001.txt"

########################################
# PHYSICAL ADMIN NODE – HEALTH
########################################
- name: Physical Admin Node Health
  hosts: physical_admin
  gather_facts: false
  vars:
    output_dir: "/tmp/hpcm_outputs/physical_admin"
  tasks:

    - name: Create physical admin output directory
      delegate_to: localhost
      file:
        path: "{{ output_dir }}"
        state: directory
        mode: '0755'

    - name: Collect Physical Admin Data
      shell: |
        set +e
        {
          echo "================ PHYSICAL ADMIN ================="

          echo "===== PCS Status ====="
          pcs status || true

          echo "===== OS ====="
          cat /etc/os-release || true

          echo "===== Kernel ====="
          uname -r || true

          echo "===== IP Addresses (ip a) ====="
          ip a || true

          echo "===== Hardware ====="
          dmidecode -t system || true

          echo "===== Filesystem ====="
          df -Th || true
        } 2>&1
      register: physical
      changed_when: false

    - name: Save Physical Admin Output
      delegate_to: localhost
      copy:
        content: "{{ physical.stdout }}"
        dest: "{{ output_dir }}/physical_admin_health.txt"
